### ISSUE TITLE
Stuck on "Please wait until download is starting"

### ISSUE THREAD

**Issue by Bagira20** [Ajatt-Tools/manyame#11]
Just as the title says, I'm able to select the series without any problems as usual, but it won't get past the "Please wait until download is starting" section, meaning the actual download doesn't start.

**Comment by moonmuaaz000** [comment]
HorribleSub is no more gotta wait for developer to UPDATE

**Comment by asakura42** [comment]
Can't reproduce. By the way it may be ok if server is busy.
