### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Bagira20** [Ajatt-Tools/manyame#2]
First up thanks for the effort! This tool seems to be incredibly helpful, but unfortunately it doesn't seem to work for me.
When I select an episode it gives me a message saying "file or directory not found".
I'm unfortunately not that well versed in terminal programming, so I apologize if this is a simple fix. 
I'm using Windows 10, by the way, in case that is important.
![example](https://user-images.githubusercontent.com/45487145/93021063-f0d21280-f5e0-11ea-814b-1f9c9a475ecd.JPG)

**Comment by whew** [comment]
Please post the output of command `uname -a` in command line

**Comment by Bagira20** [comment]
Do you mean this?
MINGW32_NT-6.2 DESKTOP-U7Q971V 1.0.19(0.48/3/2) 2016-07-13 17:45 i686 Msys

**Comment by whew** [comment]
> MINGW32_NT-6.2 DESKTOP-U7Q971V 1.0.19(0.48/3/2) 2016-07-13 17:45 i686 Msys

Yep, thx!

**Comment by whew** [comment]
@Bagira20 
Fixed, check latest release https://github.com/Ajatt-Tools/manyame/releases/tag/1.2.1

**Comment by Bagira20** [comment]
Tried it and worked without any issues! Thanks a bunch and keep up the great work!
